# Generated by Django 3.0.6 on 2020-06-11 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0002_connection_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('SAFESPACE', 'Safe Space'), ('COMMONAREA', 'Common Area'), ('KITCHEN', 'Kitchen'), ('MOVING', 'Moving'), ('RESTAURANT', 'Restaurant')], default='SAFESPACE', max_length=50)),
                ('occasion', models.CharField(choices=[('unspecified', 'Unspecified'), ('Early morning', (('planning', 'Planning'), ('working', 'Working'))), ('Breakfast', (('before meal prep', 'Before Meal Prep'), ('during meal', 'During Meal'), ('after meal prep', 'After Meal Prep'))), ('Kids at School', (('on commute', 'On Commute'), ('return home', 'Return Home'))), ('At work', (('plan for day', 'Plan for Day'), ('before meeting', 'Before Meeting'), ('during meeting', 'During Meeting'), ('after meeting', 'After Meeting'), ('roadblocked', 'Roadblocked'), ('hard at work', 'Hard at Work'), ('break', 'Break'), ('interrupted', 'Interrupted'))), ('Kids at Home', (('house chore', 'House Chore'), ('finish work', 'Finish Work'), ('spend time with children', 'Spend Time with Children'))), ('Kids asleep', (('finish up house chore', 'Finish up House Chore'), ('time with partner', 'Time with Partner'), ('alone time', 'Alone Time')))], default='unspecified', max_length=50)),
                ('involved_one', models.CharField(blank=True, choices=[('SELF', 'Self'), ('PARTNER', 'Partner'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('FRIEND', 'Friend'), ('EMPLOYER', 'Employer'), ('SUPERVISOR', 'Supervisor'), ('EMPLOYEE', 'Employee'), ('COLLEAGUE', 'Colleague'), ('RANDOM', 'Random')], default='SELF', max_length=50, null=True)),
                ('consumption', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection')),
            ],
        ),
    ]
