# Generated by Django 3.0.6 on 2020-06-11 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vice',
            name='consumption_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
