# Generated by Django 3.0.6 on 2020-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vices', '0002_vice_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vice',
            name='location',
            field=models.CharField(choices=[('Safe Space', 'Safe Space'), ('Common Area', 'Common Area'), ('Kitchen', 'Kitchen'), ('Moving', 'Moving'), ('Restaurant', 'Restaurant')], default='Safe Space', max_length=50),
        ),
    ]
