# Generated by Django 3.0.6 on 2020-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vices', '0003_auto_20200616_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vice',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='vice',
            name='involved_one',
        ),
        migrations.AlterField(
            model_name='vice',
            name='occasion',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('Early morning', (('planning', 'Planning'), ('working', 'Working'))), ('Breakfast', (('before meal prep', 'Before Meal Prep'), ('during meal', 'During Meal'), ('after meal prep', 'After Meal Prep'))), ('Kids at School', (('on commute', 'On Commute'), ('return home', 'Return Home'))), ('At work', (('plan for day', 'Plan for Day'), ('roadblocked', 'Roadblocked'), ('break', 'Break'), ('interrupted', 'Interrupted'))), ('Kids at Home', (('house chore', 'House Chore'), ('finished work', 'Finished Work'), ('spent time with children', 'Spent Time with Children'))), ('Kids asleep', (('finished house chore', 'Finished House Chore'), ('time with partner', 'Time with Partner'), ('alone time', 'Alone Time')))], default='unspecified', max_length=50),
        ),
    ]
