# Generated by Django 3.0.6 on 2020-06-26 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emotion', models.CharField(choices=[('unknown', 'Unknown'), ('Afraid', (('anxious', 'Anxious'), ('concerned', 'Concerned'), ('defensive', 'Defensive'), ('overwhelmed', 'Overwhelmed'))), ('Angry', (('annoyed', 'Annoyed'), ('bitter', 'Bitter'), ('fed up', 'Fed up'), ('jealous', 'Jealous'), ('unappreciated', 'Unappreciated'), ('upset', 'Upset'), ('vengeful', 'Vengeful'))), ('Ashamed', (('disgraced', 'Disgraced'), ('exposed', 'Exposed'), ('foolish', 'Foolish'), ('humiliated', 'Humiliated'), ('self-conscious', 'Self-conscious'), ('unworthy', 'Unworthy'), ('vulnerable', 'Vulnerable'))), ('Guilty', (('bad', 'Bad'), ('regretful', 'Regretful'), ('responsible', 'Responsible'), ('wrong', 'Wrong'))), ('Hurt', (('discarded', 'Discarded'), ('insulted', 'Insulted'), ('rejected', 'Rejected'), ('unwanted', 'Unwanted'))), ('Out of Option', (('directionless', 'Directionless'), ('lack of control', 'Lack of Control'), ('lost', 'Lost'), ('trapped', 'Trapped'), ('uncoordinated', 'Uncoordinated'))), ('Sad', (('disappointed', 'Disappointed'), ('empty', 'Empty'), ('miserable', 'Miserable'), ('trapped', 'Trapped'), ('unwanted', 'Unwanted'), ('withdrawn', 'Withdrawn'))), ('Worthy', (('deserving', 'Deserving'), ('hard working', 'Hard working'), ('small win', 'Small win'), ('proud', 'Proud')))], default='unknown', max_length=50)),
                ('reason', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
