# Generated by Django 3.0.6 on 2020-06-08 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('unknown', 'Unknown'), ('Worthy', (('deserving', 'Deserving'), ('hard working', 'Hard working'), ('small win', 'Small win'), ('proud', 'Proud'))), ('Afraid', (('anxious', 'Anxious'), ('concerned', 'Concerned'), ('defensive', 'Defensive'), ('edgy', 'Edgy'), ('overwhelmed', 'Overwhelmed'))), ('Hurt', (('discarded', 'Discarded'), ('insulted', 'Insulted'), ('rejected', 'Rejected'), ('unwanted', 'Unwanted'))), ('Guilty', (('bad', 'Bad'), ('regretful', 'Regretful'), ('responsible', 'Responsible'), ('wrong', 'Wrong'))), ('Angry', (('annoyed', 'Annoyed'), ('bitter', 'Bitter'), ('fed up', 'Fed up'), ('jealous', 'Jealous'), ('unappreciated', 'Unappreciated'), ('upset', 'Upset'), ('vengeful', 'Vengeful'))), ('Ashamed', (('disgraced', 'Disgraced'), ('exposed', 'Exposed'), ('foolish', 'Foolish'), ('humiliated', 'Humiliated'), ('self-conscious', 'Self-conscious'), ('unworthy', 'Unworthy'), ('vulnerable', 'Vulnerable'))), ('Sad', (('blue', 'Blue'), ('depressed', 'Depressed'), ('disappointed', 'Disappointed'), ('down', 'Down'), ('empty', 'Empty'), ('miserable', 'Miserable'), ('irritable', 'Irritable'), ('unwanted', 'Unwanted'), ('withdrawn', 'Withdrawn')))], default='unknown', max_length=50)),
                ('reason', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
