# Generated by Django 3.0.6 on 2020-06-05 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connection_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
