# Generated by Django 3.0.6 on 2020-06-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connection_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('Afraid', (('anxious', 'Anxious'), ('concerned', 'Concerned'), ('defensive', 'Defensive'), ('overwhelmed', 'Overwhelmed'))), ('Angry', (('annoyed', 'Annoyed'), ('bitter', 'Bitter'), ('fed up', 'Fed up'), ('jealous', 'Jealous'), ('unappreciated', 'Unappreciated'), ('upset', 'Upset'), ('vengeful', 'Vengeful'))), ('Ashamed', (('disgraced', 'Disgraced'), ('exposed', 'Exposed'), ('foolish', 'Foolish'), ('humiliated', 'Humiliated'), ('self-conscious', 'Self-conscious'), ('unworthy', 'Unworthy'), ('vulnerable', 'Vulnerable'))), ('Guilty', (('bad', 'Bad'), ('regretful', 'Regretful'), ('responsible', 'Responsible'), ('wrong', 'Wrong'))), ('Hurt', (('discarded', 'Discarded'), ('insulted', 'Insulted'), ('rejected', 'Rejected'), ('unwanted', 'Unwanted'))), ('Out of Option', (('directionless', 'Directionless'), ('lack of control', 'Lack of Control'), ('lost', 'Lost'), ('trapped', 'Trapped'), ('uncoordinated', 'Uncoordinated'))), ('Sad', (('disappointed', 'Disappointed'), ('empty', 'Empty'), ('miserable', 'Miserable'), ('trapped', 'Trapped'), ('unwanted', 'Unwanted'), ('withdrawn', 'Withdrawn'))), ('Worthy', (('deserving', 'Deserving'), ('hard working', 'Hard working'), ('small win', 'Small win'), ('proud', 'Proud')))], default='unknown', max_length=50),
        ),
    ]
