# Generated by Django 3.0.6 on 2020-06-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20200605_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
