# Generated by Django 3.0.6 on 2020-06-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_auto_20200606_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='core_emotion',
            new_name='emotion',
        ),
    ]
