# Generated by Django 3.0.6 on 2020-06-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_auto_20200607_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='emotion',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
