# Generated by Django 3.0.6 on 2020-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_auto_20200607_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='emotion',
            field=models.CharField(choices=[('Happy', (('appreciative', 'Appreciative'), ('blissful', 'Blissful'), ('confident', 'Confident'), ('connected', 'Connected'), ('encouraged', 'Encouraged'))), ('Afraid', (('anxious', 'Anxious'), ('concerned', 'Concerned'), ('defensive', 'Defensive'), ('distressed', 'Distressed'), ('edgy', 'Edgy'), ('overwhelmed', 'Overwhelmed'), ('powerless', 'Powerless'), ('worried', 'Worried'))), ('Hurt', (('discarded', 'Discarded'), ('insulted', 'Insulted'), ('rejected', 'Rejected'), ('unwanted', 'Unwanted'))), ('Guilty', (('bad', 'Bad'), ('regretful', 'Regretful'), ('responsible', 'Responsible'), ('wrong', 'Wrong'))), ('Angry', (('annoyed', 'Annoyed'), ('bitter', 'Bitter'), ('fed up', 'Fed up'), ('grumpy', 'Grumpy'), ('irritated', 'Irritated'), ('jeaous', 'Jealous'), ('upset', 'Upset'), ('vengeful', 'Vengeful'))), ('Ashamed', (('disgraced', 'Disgraced'), ('embarrassed', 'Embarrassed'), ('exposed', 'Exposed'), ('foolish', 'Foolish'), ('humiliated', 'Humiliated'), ('mortified', 'Mortified'), ('self-conscious', 'Self-conscious'), ('unworthy', 'Unworthy'), ('vulnerable', 'Vulnerable'))), ('Sad', (('blue', 'Blue'), ('depressed', 'Depressed'), ('disappointed', 'Disappointed'), ('down', 'Down'), ('empty', 'Empty'), ('miserable', 'Miserable'), ('irritable', 'Irritable'), ('unwanted', 'Unwanted'), ('withdrawn', 'Withdrawn'))), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
