# Generated by Django 3.0.6 on 2020-06-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_auto_20200607_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('Worthy', (('deserving', 'Deserving'), ('hard working', 'Hard working'), ('small win', 'Small win'), ('proud', 'Proud'))), ('Afraid', (('anxious', 'Anxious'), ('concerned', 'Concerned'), ('defensive', 'Defensive'), ('edgy', 'Edgy'), ('overwhelmed', 'Overwhelmed'))), ('Hurt', (('discarded', 'Discarded'), ('insulted', 'Insulted'), ('rejected', 'Rejected'), ('unwanted', 'Unwanted'))), ('Guilty', (('bad', 'Bad'), ('regretful', 'Regretful'), ('responsible', 'Responsible'), ('wrong', 'Wrong'))), ('Angry', (('annoyed', 'Annoyed'), ('bitter', 'Bitter'), ('fed up', 'Fed up'), ('jealous', 'Jealous'), ('unappreciated', 'Unappreciated'), ('upset', 'Upset'), ('vengeful', 'Vengeful'))), ('Ashamed', (('disgraced', 'Disgraced'), ('exposed', 'Exposed'), ('foolish', 'Foolish'), ('humiliated', 'Humiliated'), ('self-conscious', 'Self-conscious'), ('unworthy', 'Unworthy'), ('vulnerable', 'Vulnerable'))), ('Sad', (('blue', 'Blue'), ('depressed', 'Depressed'), ('disappointed', 'Disappointed'), ('down', 'Down'), ('empty', 'Empty'), ('miserable', 'Miserable'), ('irritable', 'Irritable'), ('unwanted', 'Unwanted'), ('withdrawn', 'Withdrawn')))], default='unknown', max_length=50),
        ),
    ]
