# Generated by Django 3.0.6 on 2020-06-26 02:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0002_moves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moves',
            new_name='Move',
        ),
    ]
