/*
CREATE TABLE IF NOT EXISTS core_emotion (
    id serial unique key,
    name varchar(50) NOT NULL
)
*/
INSERT INTO core_emotion (name)
VALUES ('HAPPY'), 
       ('AFRAID'),
       ('HURT'),
       ('GUILTY'),
       ('ANGRY'),
       ('ASHAMED'),
       ('SAD')

/*
CREATE TABLE IF NOT EXISTS emotion (
    id serial PRIMARY KEY,
    name varchar(50) NOT NULL,
    core_emotion_id INTEGER REFERENCES core_emotion (id)
)
*/

INSERT INTO emotion (name, core_emotion_id)
VALUES ('Appreciateive', '1'), 
       ('Blissful', '1'),
       ('Calm', '1'),
       ('Centered', '1'),
       ('Compassionate', '1'),
       ('Confident', '1'),
       ('Connected', '1'),
        ('Content', '1'),
        ('Delighted', '1'),
        ('Ecstatic', '1'), 
        ('Encouraged', '1'),
        ('Energized', '1'),
        ('Enthusiastic', '1'),
        ('Excited', '1'),
        ('Fulfilled', '1'),
        ('Glad', '1'),
        ('Grateful', '1'),
        ('Hopeful', '1'),
        ('Inspired', '1'),
        ('Joyful', '1'),
        ('Loving', '1'),
        ('Moved', '1'),
        ('Optimistic', '1'),
        ('Peaceful', '1'),
        ('Pleased', '1'),
        ('Radiant', '1'),
        ('Refreshed', '1'),
        ('Safe', '1'),
        ('Satisfied', '1'),
        ('Secure', '1'),
        ('Strong', '1'),
        ('Thankful', '1'),
        ('Touched', '1'),
        ('Alarmed', '2'),
        ('Anxious', '2'),
        ('Apprehensive', '2'),
        ('Avoidant', '2'),
        ('Concerned', '2'),
        ('Defensive', '2'),
        ('Distressed', '2'),
        ('Disturbed', '2'),
        ('Dread', '2'),
        ('Edgy', '2'),
        ('Frantic', '2'),
        ('Frightened', '2'),
        ('Helpless', '2'),
        ('Hesitant', '2'),
        ('Insecure', '2'),
        ('Mistrustful', '2'),
        ('Nervous', '2'),
        ('Overwhelmed', '2'),
        ('Panicked', '2'),
        ('Paralyzed', '2'),
        ('Petrified', '2'),
        ('Powerless', '2'),
        ('Rattled', '2'),
        ('Restless', '2'),
        ('Scared', '2'),
        ('Shaky', '2'),
        ('Shocked', '2'),
        ('Startled', '2'),
        ('Suspicious', '2'),
        ('Terrified', '2'),
        ('Uneasy', '2'),
        ('Vigilant', '2'),
        ('Wary', '2'),
        ('Worried', '2'),
        ('Baffled', '3'),
        ('Bewildered', '3'),
        ('Dazed', '3'),
        ('Dejected', '3'),
        ('Disappointed', '3'),
        ('Discarded', '3'),
        ('Insulted', '3'),
        ('Invisible', '3'),
        ('Mystified', '3'),
        ('Offended', '3'),
        ('Rejected', '3'),
        ('Unimportant', '3'),
        ('Unwanted', '3'),
        ('Bad', '4'),
        ('Culpable', '4'),
        ('Regretful', '4'),
        ('Remorseful', '4'),
        ('Responsible', '4'),
        ('Sheepish', '4'),
        ('Wrong', '4'),
        ('Agitated', '5'),
        ('Annoyed', '5'),
        ('Antagonistic', '5'),
        ('Bitter', '5'),
        ('Contemptuous', '5'),
        ('Disdainful', '5'),
        ('Disgusted', '5'),
        ('Enraged', '5'),
        ('Envious', '5'),
        ('Exasperated', '5'),
        ('Fed Up', '5'),
        ('Frustrated', '5'),
        ('Furious', '5'),
        ('Guarded', '5'),
        ('Grumpy', '5'),
        ('Hostile', '5'),
        ('Impatient', '5'),
        ('Indifferent', '5'),
        ('Indignant', '5'),
        ('Irate', '5'),
        ('Irked', '5'),
        ('Irritated', '5'),
        ('Jealous', '5'),
        ('Mad', '5'),
        ('Outraged', '5'),
        ('Peeved', '5'),
        ('Perturbed', '5'),
        ('Resentful', '5'),
        ('Upset', '5'),
        ('Vengeful', '5'),
        ('Vindictive', '5'),
        ('Chagrined', '6'),
        ('Confused', '6'),
        ('Culpable', '6'),
        ('Disgraced', '6'),
        ('Dishonorable', '6'),
        ('Embarrassed', '6'),
        ('Exposed', '6'),
        ('Flustered', '6'),
        ('Foolish', '6'),
        ('Humiliated', '6'),
        ('Improper', '6'),
        ('Mortified', '6'),
        ('Ridiculous', '6'),
        ('Self-Conscious', '6'),
        ('Shocked', '6'),
        ('Unworthy', '6'),
        ('Visible', '6'),
        ('Vulnerable', '6'),
        ('Blue', '7'),
        ('Cranky', '7'),
        ('Dark', '7'),
        ('Defeated', '7'),
        ('Depressed', '7'),
        ('Despairing', '7'),
        ('Despondent', '7'),
        ('Disappointed', '7'),
        ('Discouraged', '7'),
        ('Disheartened', '7'),
        ('Distressed', '7'),
        ('Down', '7'),
        ('Empty', '7'),
        ('Gloomy', '7'),
        ('Grieving', '7'),
        ('Hopeless', '7'),
        ('Irritable', '7'),
        ('Miserable', '7'),
        ('Morose', '7'),
        ('Sorrowful', '7'),
        ('Unhappy', '7'),
        ('Unwanted', '7'),
        ('Withdrawn', '7')