# Generated by Django 3.0.6 on 2020-07-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleact',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='scheduleact',
            name='repetiion',
        ),
    ]
