# Generated by Django 3.0.6 on 2020-07-02 20:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='tag at your convenience', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='actioncategory',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='tag at your convenience', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
