# Generated by Django 3.0.6 on 2020-07-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='act',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='act',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
