# Generated by Django 3.0.6 on 2020-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20200708_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
