# Generated by Django 3.0.6 on 2020-07-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20200702_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleAct',
        ),
    ]
