# Generated by Django 3.0.6 on 2020-07-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20200703_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='builds_confidence',
            field=models.BooleanField(default=True),
        ),
    ]
