# Generated by Django 3.0.6 on 2020-07-02 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
        ('schedules', '0003_delete_scheduleact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acts.Act')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Schedule')),
            ],
        ),
    ]
