# Generated by Django 3.0.6 on 2020-07-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20200708_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=150, unique=True),
        ),
    ]
