# Generated by Django 3.0.6 on 2020-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_act_builds_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
