# Generated by Django 3.0.6 on 2020-07-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_act_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='builds_confidence',
            field=models.IntegerField(choices=[(1, 'Up'), (0, 'Neutral'), (-1, 'Down')]),
        ),
    ]
