# Generated by Django 3.0.6 on 2020-07-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_scheduleact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleact',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
