# Generated by Django 3.0.6 on 2020-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20200704_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='acts',
            field=models.ManyToManyField(through='schedules.ScheduleAct', to='schedules.Act'),
        ),
    ]
